'use client';
import {useState} from 'react';
import {labels,services} from '@/lib/opportunities/types';
import {candidatePlatforms,type SocialCandidate} from '@/lib/opportunities/social-index-types';

export function SocialCandidates({items,ready,onChange}:{items:SocialCandidate[];ready:boolean;onChange:(id:string,status:SocialCandidate['status'])=>Promise<boolean>}){
  const [platform,setPlatform]=useState('all'),[service,setService]=useState('all'),[status,setStatus]=useState('active'),[busy,setBusy]=useState(''),[onlyBuyers,setOnlyBuyers]=useState(true);
  const visible=items.filter(c=>(!onlyBuyers||c.currentMatch!==false)&&(platform==='all'||c.platform===platform)&&(service==='all'||c.service===service)&&(status==='active'?c.status!=='dismissed':c.status===status));
  async function update(c:SocialCandidate,next:SocialCandidate['status']){setBusy(c.id);try{await onChange(c.id,next);}finally{setBusy('');}}
  function exportCsv(){const escape=(s:unknown)=>{let text=String(s??'');if(/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';};const rows=[['Platform','Title','Snippet','URL','Service','Evidence','Found at','Publication date','Verification','Status','Source'],...visible.map(c=>[labels[c.platform],c.title,c.snippet,c.url,c.service,c.evidence,c.discoveredAt,'','Unverified search snippet',c.status,c.source||'Public web search'])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='social-candidates.csv';link.click();URL.revokeObjectURL(url);}
  return <section className="opp-settings"><div className="opp-section-title"><h2>Social posts to review <span>{visible.length}</span></h2><button className="btn btn-secondary" disabled={!visible.length} onClick={exportCsv}>Export candidates</button></div>
    <p>Social post links from public search and imported alerts. These are <strong>unverified candidates</strong>, not confirmed live buying requests. Open the original post to check who is asking and whether the request is still open.</p>
    <p className="opp-help">{ready?'Using your locally hosted search engine.':'Using free public web search; no API key required.'} Search coverage varies. Rate limits and human checks pause automatic collection.</p>
    <label className="opp-option"><input type="checkbox" checked={onlyBuyers} onChange={e=>setOnlyBuyers(e.target.checked)}/>Only snippets passing current buyer-intent rules</label>
    <div className="opp-filters"><label>Social platform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">All social platforms</option>{candidatePlatforms.map(p=><option key={p} value={p}>{labels[p]}</option>)}</select></label><label>Candidate service<select value={service} onChange={e=>setService(e.target.value)}><option value="all">All services</option>{services.map(s=><option key={s}>{s}</option>)}</select></label><label>Candidate status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="saved">Saved</option><option value="dismissed">Dismissed</option></select></label></div>
    {!visible.length&&<p className="opp-help">No indexed candidates match these filters. Select social platforms in Search settings and run Find opportunities. Search engines may return no relevant posts.</p>}
    <div className="opp-source-grid">{visible.map(c=><article className="panel rounded-2xl p-5 space-y-3" key={c.id}><div className="opp-source-title"><strong>{labels[c.platform]}</strong><span>Unverified snippet</span></div><h3>{c.title}</h3><p>{c.snippet}</p><blockquote>{c.evidence}</blockquote><p className="opp-help">{c.service} · {c.source||'Public web search'} · Found {new Date(c.discoveredAt).toLocaleDateString()} · Posted date unknown</p><div className="opp-actions"><a href={c.url} className="btn btn-primary" target="_blank" rel="noreferrer">Review original post ↗</a><button disabled={busy===c.id} className="btn btn-secondary" onClick={()=>update(c,'saved')}>{c.status==='saved'?'Saved':'Save'}</button><button disabled={busy===c.id} className="btn btn-secondary" onClick={()=>update(c,c.status==='dismissed'?'new':'dismissed')}>{c.status==='dismissed'?'Restore':'Dismiss'}</button></div></article>)}</div>
  </section>;
}
